services:
  - type: we
    name: Toxic-MD
    env: docker
    region: Frankfurt
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run toshtech"
    envVars:
      - key: PORT
        value: "3000"